# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u171-jdk
      - image: redislabs/rebloom:edge
      - image: redislabs/rebloom:edge
        command: ['--port', '7379', '--loadmodule', '/usr/lib/redis/modules/redisbloom.so', '--cluster-enabled', 'yes', '--cluster-config-file /tmp/redis_cluster_node1.conf']
      - image: redislabs/rebloom:edge
        command: ['--port', '7380', '--loadmodule', '/usr/lib/redis/modules/redisbloom.so', '--cluster-enabled', 'yes', '--cluster-config-file /tmp/redis_cluster_node2.conf']
      - image: redislabs/rebloom:edge
        command: ['--port', '7381', '--loadmodule', '/usr/lib/redis/modules/redisbloom.so', '--cluster-enabled', 'yes', '--cluster-config-file /tmp/redis_cluster_node3.conf']

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
        
      # run tests!
     # - run: mvn pmd:check
      
      - run: mvn integration-test 

      - run: mvn cobertura:cobertura
      
      - run: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}  
          
      - run: mvn -s .circleci.settings.xml -DskipTests deploy

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
